### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by Mte90** [php-stubs/wp-cli-stubs#1]
* https://github.com/szepeviktor/phpstan-wordpress/blob/master/stub-generators/wp-cli-generate-stubs.sh
* Check finder in https://github.com/php-stubs/woocommerce-stubs to get inspiration
* Include and exclude stuff based on https://github.com/wp-cli/wp-cli-bundle/blob/75cb7e32de9a10a44e0e800deee72fdc224b0a01/composer.json#L12-L37

**Comment by Mte90** [comment]
Pushed a first version

**Comment by szepeviktor** [comment]
Very nice!

**Comment by Mte90** [comment]
Ref: https://github.com/php-stubs/wp-cli-stubs/pull/2
