### ISSUE TITLE
WordPress Stubs require is outdated

### ISSUE THREAD

**Issue by kallookoo** [php-stubs/wp-cli-stubs#10]
Hi,

The current version of the WordPress stubs is 6.0 and the require of the composer.json not support it. 
Please, update the composer require.

**Comment by szepeviktor** [comment]
Helli @kallookoo! 👋🏻 

Your wish is my command.

Please install `php-stubs/wp-cli-stubs:dev-master` version.

**Comment by kallookoo** [comment]
Thanks @szepeviktor
