### ISSUE TITLE
Release new version for dependency

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wp-cli-stubs#11]
Could you release a new version bc of:

>php-stubs/wp-cli-stubs[v2.5.0, ..., v2.6.0] require php-stubs/wordpress-stubs ^4.7 || ^5.0 -> found php-stubs/wordpress-stubs[v4.7.14, ..., v4.9.20, v5.0, ..., v5.9.5] but it conflicts with your root composer.json require (^6.0).

when using this with the WP stubs separately.

Are the wordpress-stubs really required to be a dependency for the CLI stubs?

While you're at it, would it be possible to regenerate stubs for CLI 2.7.0?

**Comment by szepeviktor** [comment]
Hello @kkmuffme !

> Are the wordpress-stubs really required to be a dependency for the CLI stubs?

Yes, WP-CLI uses WP core functions and classes.

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by kkmuffme** [comment]
Thanks!
