### ISSUE TITLE
Does not Find Bar and other Utils classes

### ISSUE THREAD

**Issue by tomjn** [php-stubs/wp-cli-stubs#12]
It does not find WP CLI Utils classes, giving reports such as this:

```
Call to method finish() on an unknown class WP_CLI\Utils\cli\progress\Bar. 
```
```
Call to method finish() on an unknown class WP_CLI\Utils\NoOp.
```

```
Call to method tick() on an unknown class WP_CLI\Utils\cli\progress\Bar.
```

etc

`WP_CLI\Utils` itself is stubbed, but not the classes underneath it

**Comment by szepeviktor** [comment]
Hello Tom! 👋🏻 
Thank you for your report.

Have you tried using the other two stubs?
There are three of them.

**Comment by szepeviktor** [comment]
No!!
I know these errors.
These are docblock errors in WP-CLI.

**Comment by szepeviktor** [comment]
... and it is fixed in https://github.com/wp-cli/wp-cli/pull/5715 but released yet

**Comment by szepeviktor** [comment]
You can patch the stubs temporarily.
https://github.com/wp-cli/wp-cli/commit/da64a994c73379d7388ab9c766a0c4690cd0d6b7.patch
e.g. using `sed` command
