### ISSUE TITLE
Filename error in readme?

### ISSUE THREAD

**Issue by artschekoff** [php-stubs/wp-cli-stubs#21]
In readme:
https://github.com/php-stubs/wp-cli-stubs/blob/f27ff9e8e29d7962cb070e58de70dfaf63183007/README.md?plain=1#L29-L35

**wp-cli-tools.php** does not exists, but **[wp-cli-tools-stubs.php](https://github.com/php-stubs/wp-cli-stubs/blob/master/wp-cli-tools-stubs.php)** does. After fixing this everything works, so final config is:

```

parameters:
bootstrapFiles:
  - vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php
scanFiles:
  - vendor/php-stubs/wp-cli-stubs/wp-cli-stubs.php
  - vendor/php-stubs/wp-cli-stubs/wp-cli-commands-stubs.php
  - vendor/php-stubs/wp-cli-stubs/wp-cli-i18n-stubs.php
  - vendor/php-stubs/wp-cli-stubs/wp-cli-tools-stubs.php

```

**Comment by szepeviktor** [comment]
Thank you for spotting this.

This is highly unmaintained repository.

**Comment by szepeviktor** [comment]
Thank you Artem!

You only need `wp-cli-stubs.php`.
