### ISSUE TITLE
Add WP_CLI constants

### ISSUE THREAD

**Issue by kallookoo** [php-stubs/wp-cli-stubs#6]
Hi, 
I use this stubs by the constants are missing like WP_CLI, WP_CLI_VERSION, etc...
Is possible to include? 
Thanks

**Comment by szepeviktor** [comment]
Hello! It is possible but I'd like to keep the stubs file clean.

**Comment by szepeviktor** [comment]
> WP-CLI **function and class declaration** stubs for static analysis.

**Comment by szepeviktor** [comment]
"clean" in OOP sense, not in WordPress sense

**Comment by szepeviktor** [comment]
And yes, I know WP-CLI suggests `defined('WP_CLI')`
https://github.com/wp-cli/wp-cli/blob/master/php/wp-cli.php#L4
Please create `tests/phpstan/constants.php` and put `WP_CLI` in there.

**Comment by szepeviktor** [comment]
And it feels bad to choose one way:

- support developers
- keeping it clean

**Comment by kallookoo** [comment]
Ok, I created another php with missings to include inside the vscode.
Thanks

**Comment by szepeviktor** [comment]
You may need to add it to `dynamicConstantNames:`
https://phpstan.org/config-reference#constants
