### ISSUE TITLE
WP CLI 2.6.0 stubs?

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wp-cli-stubs#9]
https://packagist.org/packages/wp-cli/wp-cli is @ 2.6.0

https://github.com/php-stubs/wp-cli-stubs/tags is @ 2.5.0

**Comment by szepeviktor** [comment]
Yes, this is a sleeping project.

**Comment by kkmuffme** [comment]
Do you accept PRs? Since there are a couple projects that rely on these CLI stubs

**Comment by szepeviktor** [comment]
Here you go @kkmuffme https://github.com/php-stubs/wp-cli-stubs/releases/tag/v2.6.0

**Comment by kkmuffme** [comment]
Thank you
